def main():
    text="TCAAGTAGAATTTACGCGCAACCCATGTCTTTCAAGTATTAGACACACATGTCTTGCGCAACCTTAGACACAGCGCAACCTCAAGTAGCGCAACCTCAAGTATCAAGTACATGTCTTGAATTTACGCGCAACCTTAGACACAGAATTTACGCGCAACCTCAAGTATCAAGTATTAGACACACATGTCTTGAATTTACGAATTTACGCGCAACCGAATTTACGCGCAACCCATGTCTTTCAAGTAGCGCAACCCATGTCTTGCGCAACCTCAAGTAGCGCAACCTCAAGTAGAATTTACGAATTTACTCAAGTACATGTCTTGAATTTACTTAGACACAGCGCAACCTTAGACACAGAATTTACTCAAGTATCAAGTATTAGACACACATGTCTTGCGCAACCGAATTTACTTAGACACAGCGCAACCCATGTCTTGAATTTACCATGTCTTGAATTTACTTAGACACAGAATTTACGAATTTACCATGTCTTTTAGACACAGCGCAACCCATGTCTTGCGCAACCCATGTCTTCATGTCTTGAATTTACTTAGACACATCAAGTATCAAGTATTAGACACATCAAGTACATGTCTTCATGTCTTGCGCAACCGAATTTACGCGCAACCTTAGACACACATGTCTTCATGTCTTTTAGACACACATGTCTTTTAGACACACATGTCTTTTAGACACACATGTCTTCATGTCTTGAATTTACGCGCAACCTTAGACACACATGTCTTCATGTCTTTCAAGTACATGTCTTGCGCAACCTTAGACACAGAATTTACTTAGACACATCAAGTAGAATTTACTCAAGTATCAAGTATCAAGTACATGTCTTTCAAGTAGCGCAACCTTAGACACAGCGCAACC"
    k=12
    res=FrequentWords(text,k)
    print(res)
def PatternCount(text,pat):
    patl=len(pat)
    textl=len(text)
    diff=textl-patl
    count=0
    for i in range(0,diff+1):
        comp=text[i:patl+i]
        if comp==pat:
            count=count+1
    return(count)
def FrequentWords(text,k):
    freqpat=[]
    co=[]
    for i in range(0,len(text)-k+1):
        pat=text[i:k+i]
        co.append(PatternCount(text,pat))
    maxcount=max(co)
    for i in range(0,len(co)):
        if co[i]==maxcount:
            freqpat.append(text[i:k+i])
    freqpat=list(set(freqpat))
    return(freqpat)
    
if __name__ == '__main__':
    main()





    
    
    
